GET http://localhost:3000/places

###

POST http://localhost:3000/places
content-type: application/json

{
    "name": "some name",
    "address": "some address",
    "phone": "some phone",
    "description": "some description"
}

###

POST http://localhost:3000/codes
content-type: application/json

{
    "type": "some type",
    "message": "some message"
}